#################################################################
# Stage 1: Create Custom Java VM for Spring Boot
##################################################################
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS CREATE-CUSTOM-JDK

WORKDIR /workspace/app

# COPY the Spring Boot application artifact from Local
COPY ./target/custom-jre-sample-0.0.1-SNAPSHOT.jar app.jar

RUN jar -xf app.jar \ 
    && jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    -q \
    --recursive \
    --multi-release 17 \
    --class-path="./BOOT-INF/lib/*" \
    --module-path="./BOOT-INF/lib/*" \
    ./app.jar > deps.info \
    && jlink --no-header-files --no-man-pages \
        --compress=2 --strip-debug \
        --add-modules  $(cat deps.info) \
        --output custom-jre 

RUN timeout 5 java \
    -XX:ArchiveClassesAtExit=./custom-jre/my-shared-libs-production.jsa \
    -jar app.jar > return.txt &\
    sleep 8 && exit

##################################################################
# Stage 2: Create User&Group and Need Zlib for JVM on Distroless Image
##################################################################
FROM mcr.microsoft.com/cbl-mariner/base/core:2.0 AS CREATE-DEPENDS-FILES

RUN mkdir /staging \
    && mkdir /staging/etc \
    && tdnf install -y --releasever=2.0 --installroot /staging zlib \
    && tdnf install -y  --releasever=2.0 shadow-utils \
    && groupadd --system -g 2000 java-app \
    && useradd -u 2000 -g java-app --shell /bin/false --home-dir /dev/null --system javauser \
    && tdnf clean all \
    # Copy user/group info to staging
    && cp /etc/passwd /staging/etc/passwd \
    && cp /etc/group /staging/etc/group \
    && mkdir /app \
    && chown -R javauser:java-app /app

##################################################################
FROM mcr.microsoft.com/cbl-mariner/distroless/minimal:2.0 AS CBLMIN
# FROM mcr.microsoft.com/cbl-mariner/distroless/base:2.0 AS CBLMIN

COPY --from=CREATE-DEPENDS-FILES /staging/ / 

ENV LANG='ja_JP.UTF-8' LANGUAGE='ja_JP:ja' LC_ALL='ja_JP.UTF-8'
ENV TZ='Asia/Tokyo'

ARG DEPENDENCY=/workspace/app/

COPY --chown=javauser:java-app --from=CREATE-DEPENDS-FILES /app /app
COPY --chown=javauser:java-app --from=CREATE-CUSTOM-JDK ${DEPENDENCY}/app.jar /app/app.jar
COPY --chown=javauser:java-app --from=CREATE-CUSTOM-JDK ${DEPENDENCY}/custom-jre /app/jre

USER javauser
ENV JAVA_HOME=/app
WORKDIR /app

ENTRYPOINT ["/app/jre/bin/java","-XX:+UseParallelGC",\
            "-XX:+TieredCompilation",\
            "-XX:SharedArchiveFile=/app/jre/my-shared-libs-production.jsa",\
            "-Xmx1g","-XX:+UseParallelGC","-XX:MaxRAMPercentage=75",\
            "-jar","/app/app.jar"]
EXPOSE 8080 