FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS CREATE-CUSTOM-JDK

WORKDIR /workspace/app

# COPY the Spring Boot application artifact from Local
COPY ./target/custom-jre-sample-0.0.1-SNAPSHOT.jar app.jar
COPY ./scripts/diff-result/deps-info-latest.txt deps-info-latest.txt

RUN jar -xf app.jar && \
    jlink --no-header-files --no-man-pages --compress=2 \
    --strip-debug \
    --add-modules $(cat deps-info-latest.txt) \
    --output custom-jre
RUN timeout 5 java \
    -XX:ArchiveClassesAtExit=./custom-jre/my-shared-libs-production.jsa \
    -jar app.jar > return.txt &\
    sleep 8 && exit
