FROM mcr.microsoft.com/openjdk/jdk:17-distroless

WORKDIR /app

ENV LANG='ja_JP.UTF-8' LANGUAGE='ja_JP:ja' LC_ALL='ja_JP.UTF-8'
ENV TZ='Asia/Tokyo'
ENV JAVA_HOME=/app

USER javausers
COPY ../target/custom-jre-sample-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-Xmx1g",\
            "-XX:+UseParallelGC",\
            "-XX:+TieredCompilation",\
            "-XX:MaxRAMPercentage=75",\
            "-jar","/app/app.jar"]
EXPOSE 8080

